[package]
name = "meilisearch-types"
version = "0.29.0"
authors = ["marin <postma.marin@protonmail.com>"]
edition = "2021"

[dependencies]
actix-web = { version = "4.0.1", default-features = false }
csv = "1.1.6"
either = { version = "1.6.1", features = ["serde"] }
milli = { git = "https://github.com/meilisearch/milli.git", tag = "v0.33.0" }
proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", optional = true }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tokio = "1.0"

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"

[features]
test-traits = ["proptest", "proptest-derive"]
