[package]
name = "meilisearch-types"
version = "0.29.1"
authors = ["marin <postma.marin@protonmail.com>"]
edition = "2021"

[dependencies]
actix-web = { version = "4.2.1", default-features = false }
csv = "1.1.6"
either = { version = "1.6.1", features = ["serde"] }
milli = { git = "https://github.com/meilisearch/milli.git", tag = "v0.33.4", default-features = false }
proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", optional = true }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
time = { version = "0.3.7", features = ["serde-well-known", "formatting", "parsing", "macros"] }
tokio = "1.0"
uuid = { version = "1.1.2", features = ["serde", "v4"] }

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
meili-snap = { path = "../meili-snap" }
insta = "1.19.1"

[features]
default = ["milli/default"]

test-traits = ["proptest", "proptest-derive"]
chinese = ["milli/chinese"]
hebrew = ["milli/hebrew"]
japanese = ["milli/japanese"]
thai = ["milli/thai"]
