[package]
name = "index-scheduler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.64"
bincode = "1.3.3"
milli = { git = "https://github.com/meilisearch/milli.git", tag = "v0.33.0" }
roaring = "0.9.0"
serde = { version = "1.0.136", features = ["derive"] }
thiserror = "1.0.30"
time = { version = "0.3.7", features = ["serde-well-known", "formatting", "parsing", "macros"] }
