[package]
name = "index-scheduler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.64"
bincode = "1.3.3"
derivative = "2.2.0"
fst = "0.4.7"
indexmap = { version = "1.8.0", features = ["serde-1"] }
log = "0.4.14"
milli = { git = "https://github.com/meilisearch/milli.git", tag = "v0.33.0" }
permissive-json-pointer = { path = "../permissive-json-pointer" }
meilisearch-types = { path = "../meilisearch-types" }
regex = "1.5.5"
either = { version = "1.6.1", features = ["serde"] }
roaring = "0.9.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = { version = "1.0.85", features = ["preserve_order"] }
thiserror = "1.0.30"
time = { version = "0.3.7", features = ["serde-well-known", "formatting", "parsing", "macros"] }
uuid = { version = "1.1.2", features = ["serde", "v4"] }
