---
on:
  push:
    tags:
      - '*'
  release:
    types: [released]

name: Publish tagged image to Docker Hub

jobs:
  docker:
    runs-on: docker
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: getmeili/meilisearch
          # Output 'latest' tag only when 'release' happen, instead of when 'push tag' event happend (default behavior).
          # See https://github.com/docker/metadata-action#latest-tag
          flavor: latest=false
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable=${{ github.event_name == 'release' && github.event.action == 'released' }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
